config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :users
  root "tweets#index"
  get '/post/hashtag/:name', to: "tweets#hashtags"
  get '/tweets/moment/:genre', to: "tweets#moment"
  get 'notifications/:id/link_through', to: 'notifications#link_through',as: :link_through

  resources :tweets, only: [:index, :new, :create, :destroy, :show] do
    resources :favorites , only: [:create, :destroy]
    collection do
      get :search,:moment
    end
    member do
      get :targets, :owners
    end
  end

  resources :users, only: [:index,:edit,:show,:update] do
    member do
      get :following, :followers, :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :retweets, only: [:new, :create, :destroy]
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :tweet
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :recommend_users, only: :link_through
  def link_through
    @notification = Notification.find(params[:id])
    @tweet = @notification.tweet
    @notification.update read: true
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.haml
%li
  = link_to "#{notification.notified_by.username}さんがあなたの記事に#{notification.notified_type}をしました", link_through_path(notification)

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    = current_user.notifications.where(read: false).count
    %span.glyphicon.glyphicon-flag
      %i.fa.fa-bell{"aria-hidden" => "true"}>
      通知
  %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
    %li.dropdown-header.text-center Notifications
    = render current_user.notifications.where(read: false).order('created_at DESC').last(5)

app/views/notifications/link_through.html.haml
= render "partial/navbar"
.wrapper
  .content.row
    .content-left.col-md-3.offset-md-1
      = render "partial/userPanel", {user: current_user}
    .col-md-4.offset-col-4.my-3
      - if @notification.present?
        .userpanel-popup
          = link_to "#{@notification.notified_by.username}", "/users/#{@notification.notified_by_id}"
          = "さんはあなたのツイートにいいね♡しました"
          .popup
            = render "partial/userpanel_popup_from_recommend" , {recommend: @notification.notified_by}
      = render "partial/tweet", {tweet: @tweet}
    .content-rihgt.col-md-3.offset-col-8
      = render partial: "partial/recommend"