config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :users
  root "tweets#index"
  get '/post/hashtag/:name', to: "tweets#hashtags"
  get '/tweets/moment/:genre', to: "tweets#moment"
  get 'notifications/:id/link_through', to: 'notifications#link_through',as: :link_through

  resources :tweets, only: [:index, :new, :create, :destroy, :show] do
    resources :favorites , only: [:create, :destroy]
    collection do
      get :search,:moment
    end
    member do
      get :targets, :owners
    end
  end

  resources :users, only: [:index,:edit,:show,:update] do
    member do
      get :following, :followers, :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :retweets, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :favorites

  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :notifications, dependent: :destroy

    # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  validates :name, presence: true, length: { maximum: 100 }
  validates :username, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }

  mount_uploader :cover , MediaUploader
  mount_uploader :avator , MediaUploader

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :recommend_users, only: [:index, :show, :favorites,:followers,:following]
  before_action :tagscount, only: [:index, :show, :favorites,:followers,:following]
  before_action :set_tweet

  def index
    @users = User.where('username LIKE(?)', "%#{params[:keyword]}%").where.not(name: current_user.name)
    respond_to do |format|
      format.html
      format.json
    end
    @tag = ""
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @users = current_user.following & @user.followers
    @tweets = @user.tweets.reverse_order
    tweet_medias = []
    @tweets.each do |tweet|
      if tweet.media.present? #compactでなくifで条件分岐
        tweet_medias << tweet
      end
    end
    @tweet_medias = tweet_medias
  end

  def favorites
    @user = User.find(params[:id])
    @users = current_user.following & @user.followers

    tweets = @user.tweets.reverse_order
    tweet_medias = []
    tweets.each do |tweet|
      if tweet.media.present? #compactでなくifで条件分岐
        tweet_medias << tweet
      end
    end
    @tweet_medias = tweet_medias

    add_tweets = []
    @favorites = Favorite.where(user_id: @user.id)
    @favorites.each do |favorite|
      id = favorite.tweet_id
      tweet = Tweet.find(id)
      add_tweets << tweet
    end
    @tweets = add_tweets
  end

  def following
    @user  = User.find(params[:id])
    @following = @user.following
    @users = current_user.following & @user.followers
    tweets = @user.tweets.reverse_order
    tweet_medias = []
    tweets.each do |tweet|
      if tweet.media.present? #compactでなくifで条件分岐
        tweet_medias << tweet
      end
    end
    @tweet_medias = tweet_medias
  end

  def followers
    @user  = User.find(params[:id])
    @followers = @user.followers
    @users = current_user.following & @user.followers
    tweets = @user.tweets.reverse_order
    tweet_medias = []
    tweets.each do |tweet|
      if tweet.media.present? #compactでなくifで条件分岐
        tweet_medias << tweet
      end
    end
    @tweet_medias = tweet_medias
  end

  private
  def user_params
    params.require(:user).permit(:name, :username ,:about, :location, :website, :avator, :cover)
  end

  def set_tweet
    @tweet = Tweet.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.profileEdit
  = form_for(current_user,html: {class: 'post_photo'})  do |f|
    .profileEdit__header
      .profileEdit__header__center
        %i.fas.fa-arrow-left.fa-2x.profileEdit__header__center--icon
        .profileEdit__header__center--title プロフィール編集
        .profileEdit__header__center--position
          = f.submit "保存", type: "submit" , class: "profileEdit__header__center--btn"
    .profileEdit__form
      .profileEdit__form__cover__preview
        - if current_user.cover.present?
          = image_tag current_user.cover.url, class: 'profileEdit__form__cover  image_trimming'
      .profileEdit__form__cover
        %label.profileEdit__form__cover--icon
          %i.fas.fa-camera.fa-3x
          = f.file_field :cover , class: "profileEdit__form__cover--form"
      .profileEdit__form__avater__preview
        - if current_user.avator.present?
          = image_tag current_user.avator.url, class: 'rounded-circle image_trimming',width: "150",height: "150"
      .profileEdit__form__avater
        %label.profileEdit__form__avater--icon
          %i.fas.fa-camera.fa-2x
          = f.file_field :avator , class: "profileEdit__form__avater--form"
      .profileEdit__form__body
        .profileEdit__form__letter 名前
        .cp_iptxt.ef
          = f.text_field :name, placeholder: "名前"
        .profileEdit__form__letter @ユーザーネーム
        .cp_iptxt.ef
          = f.text_field :username, placeholder: "＠ユーザーネーム"
        .profileEdit__form__letter 自己紹介
        .cp_iptxt.ef
          = f.text_field :about, placeholder: "自己紹介"
        .profileEdit__form__letter 場所
        .cp_iptxt.ef
          = f.text_field :location, placeholder: "場所"
        .profileEdit__form__letter ウェブサイト
        .cp_iptxt.ef
          = f.text_field :website, placeholder: "ウェブサイト"

app/views/users/favorites.html.haml
= render "partial/navbar"
.wrapper
  .container-fluid
    - if @user.cover.present?
      = image_tag @user.cover.url, class: 'img-fluid header-pic image_trimming'
    - else
      = image_tag "/images/cover.jpeg", class: 'img-fluid header-pic image_trimming'
  %nav.navbar.navbar-expand-lg.bg-light.navbar-light.row
    %ul.navbar-nav.col-md-4.offset-md-4
      %li.nav-item.col-md-3
        = link_to "ツイート", user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.tweets.count}", user_path(@user.id) ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロー", "/users/#{@user.id}/following",class: 'nav-link nav-link-word'
        = link_to "#{@user.following.count}", "/users/#{@user.id}/following",class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロワー", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-word'
        = link_to "#{@user.followers.count}", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "いいね", favorites_user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.favorites.count}", favorites_user_path(@user.id),class: 'nav-link nav-link-number'
    - if user_signed_in? && current_user.id == @user.id
      = link_to "プロフィールを編集", "/users/#{current_user.id}/edit" ,class: ' btn btn-outline-secondary col-md-2 offset-md-1'
    = render "partial/follow_form" ,{user: @user}
  - if @user.avator.present?
    = image_tag @user.avator.url, class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  .container-fluid
    .wrapper
      .dashboard.row
        .content-left.col-md-3.offset-md-1
          .my-4
            .card-body
              .card-body-title #{@user.name}
              %table
                %tr
                  .card-text.text-secondary #{"@"+ @user.username}
                %tr
                  %td.fas.fa-map-marker-alt
                  %td.card-text{style: "word-break: break-all;"} #{@user.location}
                %tr
                  %td.fas.fa-link
                  %td.card-text{style: "word-break: break-all;"} #{@user.website}
                %tr
                  %td.far.fa-comment
                  %td.card-text{style: "word-break: break-all;"} #{@user.about}
                - if @users.present? && !(current_user.id == @user.id)
                  %tr
                    %td.fas.fa-users
                    %td.card-text{style: "word-break: break-all;"} #{@users.count}人の知り合いのフォロワー
              - if @users.present? && !(current_user.id == @user.id)
                - @users.each do |user|
                  = link_to (user_path(user)) do
                    - if user.avator.present?
                      = image_tag user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
                    - else
                      = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
              - if @tweet_medias.present?
                %table
                  %tr
                    %td.far.fa-images
                    %td.card-text 画像/動画
                - @tweet_medias.first(9).each do |tweet_media|
                  =link_to (tweet_path(tweet_media)) do
                    = image_tag tweet_media.media.url, class: 'my-1 image_trimming', width: "70",height: "70"

        .content-timeline.col-md-4.my-3
          = render partial: "partial/tweet", collection: @tweets
        .content-timeline.col-md-3.my-3
          = render partial: "partial/recommend"
          .my-4
            = render partial: "partial/time_trend",locals:{trend: @trend, day_trend: @day_trend, week_trend: @week_trend}

app/views/users/followers.html.haml
= render "partial/navbar"
.wrapper
  .container-fluid
    - if @user.cover.present?
      = image_tag @user.cover.url, class: 'img-fluid header-pic image_trimming'
    - else
      = image_tag "/images/cover.jpeg", class: 'img-fluid header-pic image_trimming'
  %nav.navbar.navbar-expand-lg.bg-light.navbar-light.row
    %ul.navbar-nav.col-md-4.offset-md-4
      %li.nav-item.col-md-3
        = link_to "ツイート", user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.tweets.count}", user_path(@user.id) ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロー", "/users/#{@user.id}/following",class: 'nav-link nav-link-word'
        = link_to "#{@user.following.count}", "/users/#{@user.id}/following",class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロワー", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-word'
        = link_to "#{@user.followers.count}", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "いいね", favorites_user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.favorites.count}", favorites_user_path(@user.id),class: 'nav-link nav-link-number'
    - if user_signed_in? && current_user.id == @user.id
      = link_to "プロフィールを編集", "/users/#{current_user.id}/edit" ,class: ' btn btn-outline-secondary col-md-2 offset-md-1'
    = render "partial/follow_form" ,{user: @user}
  - if @user.avator.present?
    = image_tag @user.avator.url, class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  .container-fluid
    .wrapper
      .dashboard.row
        .content-left.col-md-3.offset-md-1
          .my-4
            .card-body
              .card-body-title #{@user.name}
              %table
                %tr
                  .card-text.text-secondary #{"@"+ @user.username}
                %tr
                  %td.fas.fa-map-marker-alt
                  %td.card-text{style: "word-break: break-all;"} #{@user.location}
                %tr
                  %td.fas.fa-link
                  %td.card-text{style: "word-break: break-all;"} #{@user.website}
                %tr
                  %td.far.fa-comment
                  %td.card-text{style: "word-break: break-all;"} #{@user.about}
                - if @users.present? && !(current_user.id == @user.id)
                  %tr
                    %td.fas.fa-users
                    %td.card-text{style: "word-break: break-all;"} #{@users.count}人の知り合いのフォロワー
              - if @users.present? && !(current_user.id == @user.id)
                - @users.each do |user|
                  = link_to (user_path(user)) do
                    - if user.avator.present?
                      = image_tag user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
                    - else
                      = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
              - if @tweet_medias.present?
                %table
                  %tr
                    %td.far.fa-images
                    %td.card-text 画像/動画
                - @tweet_medias.first(9).each do |tweet_media|
                  =link_to (tweet_path(tweet_media)) do
                    = image_tag tweet_media.media.url, class: 'my-1 image_trimming', width: "70",height: "70"
          = render partial: "partial/recommend"
          .my-4
            = render partial: "partial/time_trend",locals:{trend: @trend, day_trend: @day_trend, week_trend: @week_trend}
        .content__timeline.col-md-8
          .row-eq-height.my-4
            - @followers.each do |user|
              = render "partial/userCard" , {user: user}

app/views/users/following.html.haml
= render "partial/navbar"
.wrapper
  .container-fluid
    - if @user.cover.present?
      = image_tag @user.cover.url, class: 'img-fluid header-pic image_trimming'
    - else
      = image_tag "/images/cover.jpeg", class: 'img-fluid header-pic image_trimming'
  %nav.navbar.navbar-expand-lg.bg-light.navbar-light.row
    %ul.navbar-nav.col-md-4.offset-md-4
      %li.nav-item.col-md-3
        = link_to "ツイート", user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.tweets.count}", user_path(@user.id) ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロー", "/users/#{@user.id}/following",class: 'nav-link nav-link-word'
        = link_to "#{@user.following.count}", "/users/#{@user.id}/following",class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロワー", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-word'
        = link_to "#{@user.followers.count}", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "いいね", favorites_user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.favorites.count}", favorites_user_path(@user.id),class: 'nav-link nav-link-number'
    - if user_signed_in? && current_user.id == @user.id
      = link_to "プロフィールを編集", "/users/#{current_user.id}/edit" ,class: ' btn btn-outline-secondary col-md-2 offset-md-1'
    = render "partial/follow_form" ,{user: @user}
  - if @user.avator.present?
    = image_tag @user.avator.url, class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  .container-fluid
    .wrapper
      .dashboard.row
        .content-left.col-md-3.offset-md-1
          .my-4
            .card-body
              .card-body-title #{@user.name}
              %table
                %tr
                  .card-text.text-secondary #{"@"+ @user.username}
                %tr
                  %td.fas.fa-map-marker-alt
                  %td.card-text{style: "word-break: break-all;"} #{@user.location}
                %tr
                  %td.fas.fa-link
                  %td.card-text{style: "word-break: break-all;"} #{@user.website}
                %tr
                  %td.far.fa-comment
                  %td.card-text{style: "word-break: break-all;"} #{@user.about}
                - if @users.present? && !(current_user.id == @user.id)
                  %tr
                    %td.fas.fa-users
                    %td.card-text{style: "word-break: break-all;"} #{@users.count}人の知り合いのフォロワー
              - if @users.present? && !(current_user.id == @user.id)
                - @users.each do |user|
                  = link_to (user_path(user)) do
                    - if user.avator.present?
                      = image_tag user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
                    - else
                      = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
              - if @tweet_medias.present?
                %table
                  %tr
                    %td.far.fa-images
                    %td.card-text 画像/動画
                - @tweet_medias.first(9).each do |tweet_media|
                  =link_to (tweet_path(tweet_media)) do
                    = image_tag tweet_media.media.url, class: 'my-1 image_trimming', width: "70",height: "70"
          = render partial: "partial/recommend"
          .my-4
            = render partial: "partial/time_trend",locals:{trend: @trend, day_trend: @day_trend, week_trend: @week_trend}
        .content__timeline.col-md-8
          .row-eq-height.my-4
            - @following.each do |user|
              = render "partial/userCard" , {user: user}

app/views/users/index.html.haml
= render "partial/navbar"
= render "partial/searchBar",{keyword: params[:keyword],tag: @tag}
.wrapper
  .content.row
    .content-left.col-md-3.offset-md-1
      = render partial: "partial/recommend"
      .my-4
        = render partial: "partial/time_trend",locals:{trend: @trend, day_trend: @day_trend, week_trend: @week_trend}
    .content__timeline.col-md-8
      .row-eq-height.my-4
        - @users.each do |user|
          = render "partial/userCard" , {user: user}

app/views/users/show.html.haml
= render "partial/navbar"
.wrapper
  .container-fluid
    - if @user.cover.present?
      = image_tag @user.cover.url, class: 'img-fluid header-pic image_trimming'
    - else
      = image_tag "/images/cover.jpeg", class: 'img-fluid header-pic image_trimming'
  %nav.navbar.navbar-expand-lg.bg-light.navbar-light.row
    %ul.navbar-nav.col-md-4.offset-md-4
      %li.nav-item.col-md-3
        = link_to "ツイート", user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.tweets.count}", user_path(@user.id) ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロー", "/users/#{@user.id}/following",class: 'nav-link nav-link-word'
        = link_to "#{@user.following.count}", "/users/#{@user.id}/following",class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "フォロワー", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-word'
        = link_to "#{@user.followers.count}", "/users/#{@user.id}/followers" ,class: 'nav-link nav-link-number'
      %li.nav-item.col-md-3
        = link_to "いいね", favorites_user_path(@user.id) ,class: 'nav-link nav-link-word'
        = link_to "#{@user.favorites.count}", favorites_user_path(@user.id),class: 'nav-link nav-link-number'
    - if user_signed_in? && current_user.id == @user.id
      = link_to "プロフィールを編集", "/users/#{current_user.id}/edit" ,class: ' btn btn-outline-secondary col-md-2 offset-md-1'
    = render "partial/follow_form" ,{user: @user}
  - if @user.avator.present?
    = image_tag @user.avator.url, class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle showCirclePosition image_trimming',alt: "Cinque Terre", width: "250",height: "250"
  .container-fluid
    .wrapper
      .dashboard.row
        .content-left.col-md-3.offset-md-1
          .my-4
            .card-body
              .card-body-title #{@user.name}
              %table
                %tr
                  .card-text.text-secondary #{"@"+ @user.username}
                %tr
                  %td.fas.fa-map-marker-alt
                  %td.card-text{style: "word-break: break-all;"} #{@user.location}
                %tr
                  %td.fas.fa-link
                  %td.card-text{style: "word-break: break-all;"} #{@user.website}
                %tr
                  %td.far.fa-comment
                  %td.card-text{style: "word-break: break-all;"} #{@user.about}
                - if @users.present? && !(current_user.id == @user.id)
                  %tr
                    %td.fas.fa-users
                    %td.card-text{style: "word-break: break-all;"} #{@users.count}人の知り合いのフォロワー
              - if @users.present? && !(current_user.id == @user.id)
                - @users.each do |user|
                  = link_to (user_path(user)) do
                    - if user.avator.present?
                      = image_tag user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
                    - else
                      = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
              - if @tweet_medias.present?
                %table
                  %tr
                    %td.far.fa-images
                    %td.card-text 画像/動画
                - @tweet_medias.first(9).each do |tweet_media|
                  =link_to (tweet_path(tweet_media)) do
                    = image_tag tweet_media.media.url, class: 'my-1 image_trimming', width: "70",height: "70"
        .content-timeline.col-md-4.my-3
          = render partial: "partial/tweet", collection: @tweets
        .content-timeline.col-md-3.my-3
          = render partial: "partial/recommend"
          .my-4
            = render partial: "partial/time_trend",locals:{trend: @trend, day_trend: @day_trend, week_trend: @week_trend}