config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :users
  root "tweets#index"
  get '/post/hashtag/:name', to: "tweets#hashtags"
  get '/tweets/moment/:genre', to: "tweets#moment"
  get 'notifications/:id/link_through', to: 'notifications#link_through',as: :link_through

  resources :tweets, only: [:index, :new, :create, :destroy, :show] do
    resources :favorites , only: [:create, :destroy]
    collection do
      get :search,:moment
    end
    member do
      get :targets, :owners
    end
  end

  resources :users, only: [:index,:edit,:show,:update] do
    member do
      get :following, :followers, :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :retweets, only: [:new, :create, :destroy]
end

app/views/partial/_follow.html.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  = hidden_field_tag :following_id, user.id
  = f.submit "フォロー", class: "small btn btn-sm badge-pill btn-outline-primary"

app/views/partial/_moment.html.haml
.pt-md-2
  .card
    .p-md-3
      .row
        .col-md-8
          %h3
            = moment["title"]
          %h4.badge.badge-secondary
            = moment["source"]["name"]
          %p
            = moment["description"]
          = link_to "View details »", "#{moment["url"]} " ,class:"img-responsive"
          %button.btn.btn-sm.badge-pill.btn-primary.ml-md-3{"data-target": "#momentModal", "data-toggle": "modal", type: "button" ,"data-title": "#{moment["title"]}","data-url": "#{moment["url"]}"}
            ツイート
          %a.btn.btn-sm.badge-pill.btn-success{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseExample-#{i}", :role => "button"}
            ツイート一覧
          #momentModal.modal.fade{"aria-hidden": "true", "aria-labelledby": "momentModalLabel", role: "dialog", tabindex: "-1"}
            .modal-dialog{role:"document"}
              .modal-content
                .modal-header
                  %h5#momentModalLabel.modal-title この記事のツイート
                  %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
                    %span{"aria-hidden": "true"} ×
                .modal-body
                  .card.tweet_form_body
                    = form_for Tweet.new , remote: true do |f|
                      = f.text_area :text, class: 'my-4 col-md-10 offset-md-1 form-rounded form-control tweet_form_content tweet_moment_content',rows: "10"
                      .content__timeline__photo
                      %label.offset-md-7.my-1
                        = fa_icon 'picture', class: 'fa fa-image'
                        = f.file_field "media" , class: 'tweet_form_content_image displaynone'
                      = f.hidden_field :parent_id, value: ""
                      = f.submit '新しいツイート',type: "submit", class: 'btn btn-sm badge-pill btn-primary float-right mb-md-3 mr-md-4', id: "modal-submit"
        .col-md-4
          = image_tag "#{moment["urlToImage"]}", class:"news-image"
        .col-md-1
        .col-md-10
          %div{ id: "collapseExample-#{i}" ,class: "collapse" }
            - title = moment["title"]
            - tags = Tag.where(name: title.gsub(" ", "").gsub( "\/" , "／").gsub( "\[" , "(").gsub( "\]" , ")").gsub( "\." , ","))
            - tags.each do |tag|
            - @tweets = tag.tweets
              = render partial: "partial/tweet", collection: @tweets

app/views/partial/_navbar.html.haml
.shadow-sm.sticky-top
  #user-search-result.list-group
  %nav.navbar.navbar-light.navbar-expand-lg.border-bottom{:style => "background-color: white;"}
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.ml-md-5
        %li.nav-item.small
          = link_to "ホーム", root_path, method: :get, class: 'nav-link'
        %li.nav-item.small
          = link_to "モーメント", moment_tweets_path ,class: 'nav-link'
        %li.nav-item.small
          %a.nav-link{href: "#"} 通知
        %li.nav-item.small
          %a.nav-link{href: "#"} メッセージ
      = form_tag('/users', method: :get, class: "form-inline") do
        = text_field_tag :name, "",placeholder: "ユーザー&ツイート検索",class: 'form-control mr-sm-1 form-control-sm',name: "keyword",id:'user-search-field',autocomplete: "off"
        = button_tag(type: "submit", class: "btn btn-default mr-sm-2 search-btn-color") do
          %i.fas.fa-search
      = render 'notifications/notification_dropdown'
      = link_to "/users/#{current_user.id}" , class: "mr-md-3"do
        .tweet__left--user-avatar
          - if current_user.avator.present?
            = image_tag current_user.avator.url, class: 'rounded-circle image_trimming',alt: "Cinque Terre", width: "40",height: "40"
          - else
            = image_tag "/images/person.jpg", class: 'rounded-circle image_trimming',alt: "Cinque Terre", width: "40",height: "40"
      .btn-group.dropdown-color{"aria-label" => "Button group with nested dropdown", :role => "group"}
        .btn-group{:role => "group"}
          %button.btn.btn-outline-primary.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          .dropdown-menu{"aria-labelledby" => "btnGroupDrop1"}
            = link_to "プロフィール", "/users/#{current_user.id}" ,class: 'dropdown-item'
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item'
      %button.btn.btn-sm.badge-pill.btn-primary.mx-2.mr-md-5{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
        ツイート
      #myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
        .modal-dialog.modal-dialog-centered{:role => "document"}
          .modal-content
            .modal-header
              %h5.modal-title 新しいツイート
              %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
                %span{"aria-hidden" => "true"} ×
            .modal-body
              = render 'partial/tweetForm'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon

app/views/partial/_popup_recommend.html.haml
.card.popupcardBody{ style: "width: 18rem;"}
  - if recommend.cover.present?
    = link_to "/users/#{recommend.id}" ,class: 'thumbnail' do
      = image_tag recommend.cover.url, class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - else
    = link_to "/users/#{recommend.id}" ,class: 'thumbnail' do
      = image_tag "/images/cover.jpeg", class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - if recommend.avator.present?
    = image_tag recommend.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  .card-body
    .card-body-title #{recommend.name}
    .btn-right
      = render "partial/follow_form" , {user: recommend}
    %h8.card-text.text-secondary @#{recommend.username}
    %p.card-text
      = truncate(recommend.about, length:40)
    .body-bottom.d-md-inline-flex
      = link_to "ツイート:#{recommend.tweets.count}", user_path(recommend.id), class: 'text-muted card-link'
      = link_to "フォロー:#{recommend.following.count}", following_user_path(recommend.id), class: 'text-muted card-link'
      = link_to "フォロワー:#{recommend.followers.count}", followers_user_path(recommend.id), class: 'text-muted card-link'

app/views/partial/_recommend.html.haml
.h6.font-weight-bold
  .my-2
    おすすめユーザー
- @recommends.each do |recommend|
  = render "partial/recommend_panel", {recommend: recommend}

app/views/partial/_recommend_panel.html.haml
.wrapper.card.my-2
  .recommend.card-body.row
    .recommend__left.col-md-2
      = link_to "/users/#{recommend.id}" do
        .recommend__left--user-avatar
          - if recommend.avator.present?
            = image_tag recommend.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
          - else
            = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
    .recommend__right.col-md-10
      .recommend__right--header
        .userpanel-popup
          = link_to "/users/#{recommend.id}" do
            %strong.linkcolorblack
              #{recommend.name}
            .popup
              = render "partial/userpanel_popup_from_recommend" , {recommend: recommend}
        %h6.card-subtitle.mb-2.text-muted.d-inline
          = "@#{recommend.username}"
    %a.col-md-4.offset-md-8
      = render "partial/follow_form" , {user: recommend}

app/views/partial/_searchBar.html.haml
%nav.border-bottom
  - if tag.present?
    .navbar-brand.text-primary.ml-md-5『##{tag.name}』
  - else
    .navbar-brand.text-primary.ml-md-5  KEYWORD 『#{params[:keyword]}』
  = link_to "ユーザー検索", users_path(keyword: params[:keyword]) ,class: 'badge badge-primary float-right mt-md-3 mr-md-5'
  = link_to "ツイート検索", search_tweets_path(keyword: params[:keyword]) ,class: 'badge badge-primary float-right mt-md-3 mr-md-2'

app/views/partial/_trend.html.haml
= link_to "/post/hashtag/#{trend.name}" ,class: "replyblue" do
  %h6 ##{trend.name}
%p.small #{trend.tags_count}件のツイート

app/views/partial/_tweet.html.haml
.wrapper.card.my-2.tweet-color.tweet_original{ "data-id": tweet.id}
  .tweet.card-body.row
    .tweet__left.col-md-2
      = link_to "/users/#{tweet.user_id}" do
        .tweet__left--user-avatar
          - if tweet.user.avator.present?
            = image_tag tweet.user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
          - else
            = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "50",height: "50"
    .tweet__right.col-md-10
      .tweet__right--header
        %input.user_info{type: "hidden",value: "#{tweet.user_id}"}
      .userpanel-popup
        = link_to"/users/#{tweet.user.id}" do
          %strong.linkcolorblack.d-inline
            = tweet.user.name
          .popup
            = render "partial/userpanel_popup_from_tweet" , {tweet: tweet}
        %h6.card-subtitle.mb-2.text-muted.d-inline
          = "@#{tweet.user.username}"
        %h6.card-subtitle.mb-2.text-muted.d-inline
          = link_to "#{tweet.created_at.to_s(:human)}", tweet_path(id: tweet.id)
      .btn-group.float-right
        - if tweet.user_id == current_user.id
          - if tweet.owners.present?
          - else
            = link_to tweet_path(id: tweet.id), method: "delete", data: {confirm: '本当に削除しますか？'} do
              %i.fas.fa-eraser
      .tweet__right--main
        - if tweet.parent_id?
          .tweet__right--reply
            = "返信先:"
            - parent_tweet = Tweet.find(tweet.parent_id)
            = link_to "@#{parent_tweet.user.username}", user_path(id: parent_tweet.user_id), class: "replyblue"
            %br
        - else
        .card-title
          = text_url_to_link_with_hashtags("#{simple_format(h(tweet.text))}")
          - if tweet.targets.present?
            = render partial: "partial/tweet", collection: tweet.targets
      .tweet__right--media
        = image_tag tweet.media.url, class: 'img-fluid' if tweet.media.present?
      .tweet__right--bottom
        %a.text-muted
          .tweet__right--reply.float-left
            %label.reply
              = link_to tweet_path(id: tweet.id) do
                %i.fas.fa-reply
            .reply_popup
              返信
          .tweet__right--retweet.float-left
            - if tweet.retweet?(tweet)
            -else
              = link_to new_retweet_path(id: tweet.id) do
                %i.fas.fa-retweet
            = tweet.owners.count
            .retweet_popup
              リツイート
          .tweet__right--favorite.float-left
            = render "partial/favorite" , {tweet: tweet}
            .favorite_popup
              いいね

app/views/partial/_tweetForm.html.haml
.card.tweet_form_body
  = form_for Tweet.new , remote: true do |f|
    = f.text_area :text, class: 'my-4 col-md-10 offset-md-1 form-rounded form-control tweet_form_content ', placeholder: 'いまどうしてる？',rows: "4"
    .content__timeline__photo
    %label.offset-md-7.my-1
      = fa_icon 'picture', class: 'fa fa-image'
      = f.file_field "media" , class: 'tweet_form_content_image displaynone'
    = f.hidden_field :parent_id, value: ""
    = f.submit '新しいツイート',type: "submit", class: 'btn btn-sm badge-pill btn-primary float-right mb-md-3 mr-md-4'

app/views/partial/_userCard.html.haml
.card.cardBody{ style: "width: 18rem;"}
  - if user.cover.present?
    = link_to "/users/#{user.id}" ,class: 'thumbnail' do
      = image_tag user.cover.url, class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - else
    = link_to "/users/#{user.id}" ,class: 'thumbnail' do
      = image_tag "/images/cover.jpeg", class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - if user.avator.present?
    = image_tag user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  .card-body
    .card-body-title #{user.name}
    .btn-right
      = render "partial/follow_form" , {user: user}
    %h8.card-text.text-secondary @#{user.username}
    %p.card-text
      = truncate(user.about, length:40)

app/views/partial/_userPanel.html.haml
.card.my-4.position_relative
  - if user.cover.present?
    = link_to "/users/#{user.id}" ,class: 'thumbnail' do
      = image_tag user.cover.url, class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - else
    = link_to "/users/#{user.id}" ,class: 'thumbnail' do
      = image_tag "/images/cover.jpeg", class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - if user.avator.present?
    = image_tag user.avator.url, class: 'rounded-circle circle_image_potision image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle circle_image_potision image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  .card-body
    .card-body-title #{user.name}
    %h8.card-text.text-secondary #{"@"+user.username}
    %p.card-text #{user.about}
    .body-bottom.d-md-inline-flex
      %li.nav-item.col-md-4
        = link_to "ツイート", user_path(id: current_user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{current_user.tweets.count}", user_path(id: current_user.id), class: 'text-muted card-link card-link-number'
      %li.nav-item.col-md-4
        = link_to "フォロー", following_user_path(current_user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{current_user.following.count}", following_user_path(current_user.id), class: 'text-muted card-link card-link-number'
      %li.nav-item.col-md-4
        = link_to "フォロワー", followers_user_path(current_user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{current_user.followers.count}", followers_user_path(current_user.id), class: 'text-muted card-link card-link-number'

app/views/partial/_userpanel_popup_from_recommend.html.haml
.card.popupcardBody{ style: "width: 20rem;"}
  - if recommend.cover.present?
    = link_to "/users/#{recommend.id}" ,class: 'thumbnail' do
      = image_tag recommend.cover.url, class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - else
    = link_to "/users/#{recommend.id}" ,class: 'thumbnail' do
      = image_tag "/images/cover.jpeg", class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - if recommend.avator.present?
    = image_tag recommend.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  .card-body
    .card-body-title #{recommend.name}
    .btn-right
      = render "partial/follow_form" , {user: recommend}
    %h8.card-text.text-secondary @#{recommend.username}
    %p.card-text
      = truncate(recommend.about, length:40)
    .body-bottom.d-md-inline-flex
      %li.nav-item.col-md-4
        = link_to "ツイート", user_path(recommend.id), class: 'text-muted card-link card-link-word'
        = link_to "#{recommend.tweets.count}", user_path(recommend.id), class: 'text-muted card-link card-link-number'
      %li.nav-item.col-md-4
        = link_to "フォロー", following_user_path(recommend.id), class: 'text-muted card-link card-link-word'
        = link_to "#{recommend.following.count}", following_user_path(recommend.id), class: 'text-muted card-link card-link-number'

      %li.nav-item.col-md-4
        = link_to "フォロワー", followers_user_path(recommend.id), class: 'text-muted card-link card-link-word'
        = link_to "#{recommend.followers.count}", followers_user_path(recommend.id), class: 'text-muted card-link card-link-number'

app/views/partial/_userpanel_popup_from_tweet.html.haml
.card.popupcardBody{ style: "width: 20rem;"}
  - if tweet.user.cover.present?
    = link_to "/users/#{tweet.user.id}" ,class: 'thumbnail' do
      = image_tag tweet.user.cover.url, class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - else
    = link_to "/users/#{tweet.user.id}" ,class: 'thumbnail' do
      = image_tag "/images/cover.jpeg", class: 'card-img-top image_trimming',alt: "Card image cap", width: "256", height: "100"
  - if tweet.user.avator.present?
    = image_tag tweet.user.avator.url, class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  - else
    = image_tag "/images/person.jpg", class: 'rounded-circle circlePosition image_trimming',alt: "Cinque Terre", width: "70",height: "70"
  .card-body
    .card-body-title #{tweet.user.name}
    .btn-right
      = render "partial/follow_form" , {user: tweet.user}
    %h8.card-text.text-secondary @#{tweet.user.username}
    %p.card-text
      = truncate(tweet.user.about, length:40)
    .body-bottom.d-md-inline-flex
      %li.nav-item.col-md-4
        = link_to "ツイート", user_path(tweet.user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{tweet.user.tweets.count}", user_path(tweet.user.id), class: 'text-muted card-link card-link-number'
      %li.nav-item.col-md-4
        = link_to "フォロー", following_user_path(tweet.user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{tweet.user.following.count}", following_user_path(tweet.user.id), class: 'text-muted card-link card-link-number'
      %li.nav-item.col-md-4
        = link_to "フォロワー", followers_user_path(tweet.user.id), class: 'text-muted card-link card-link-word'
        = link_to "#{tweet.user.followers.count}", followers_user_path(tweet.user.id), class: 'text-muted card-link card-link-number'